# Exploración y limpieza del dataset
### Librerías

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

### Acceso a los datos

In [2]:
ruta_catalogo = '../RAW_DATA/catalogo_productos.csv'
ruta_ventas = '../RAW_DATA/ventas_ficticias_santiago_202612.csv'
df_catalogo = pd.read_csv(ruta_catalogo,
                          dtype={'SKU': object,
                                 "Descripción SKU": object,
                                 "Tipo_embalaje": object})
df_ventas = pd.read_csv(ruta_ventas,
                        dtype={'RUT': object,
                               "Nombre cliente": object,
                               "Número de Orden": object},
                        parse_dates=['Fecha de Pedido',
                                     'Fecha de despacho Solicitada'])

### Ver Tablas

In [3]:
display(df_catalogo.head())

,SKU,Descripción SKU,Largo_cm,Ancho_cm,Alto_cm,Volumen_unitario_m3,Peso_unitario_kg,Tipo_embalaje
0,SKU-00001,Martillo carpintero,33.4,11.5,4.1,0.001575,1.006,A granel
1,SKU-00002,Escalera aluminio 4 peldaños,118.8,44.3,14.5,0.076311,7.662,Embalaje personalizado
2,SKU-00003,Cinta aisladora,10.1,9.8,1.9,0.000188,0.131,A granel
3,SKU-00004,Silicona cartucho,22.8,4.9,5.1,0.000570,0.290,A granel
4,SKU-00005,Lámpara mesa,36.5,24.7,24.7,0.022268,2.362,Caja propia

In [4]:
display(df_ventas.head())

,RUT,Nombre cliente,Dirección cliente,Fecha de Pedido,Número de Orden,Monto Pedido,Fecha de despacho Solicitada
0,14512240-4,Cliente Nuevo 14512240,AV. MATTA 5370 DEPTO 994 ESTACIÓN CENTRAL SANT...,2026-12-01,ORD-CL-202612-000001,123929,2026-12-02
1,17.313.403-1,Cliente 17313403,"Av. La Florida 7678, Macul, Santiago, Chile",2026-12-01,ORD-CL-202612-000002,118942,2026-12-03
2,7941056 - 6,Cliente Nuevo 7941056,"av. kennedy 5315, depto 694, independencia, sa...",2026-12-01,ORD-CL-202612-000003,115798,2026-12-04
3,18.305.966-9,Cliente 18305966,"Calle San Antonio 8832, Lo Prado, Santiago, Chile",2026-12-01,ORD-CL-202612-000004,240273,2026-12-03
4,20.329.309-9,Cliente Nuevo 20329309,Calle Catedral 6899 Depto 1132 Independencia S...,2026-12-01,ORD-CL-202612-000005,230875,2026-12-04

### Verificar datos
#### catálogo

In [5]:
df_catalogo.dtypes

SKU                     object
Descripción SKU         object
Largo_cm               float64
Ancho_cm               float64
Alto_cm                float64
Volumen_unitario_m3    float64
Peso_unitario_kg       float64
Tipo_embalaje           object
dtype: object

In [6]:
catalogo_numeric = df_catalogo.select_dtypes(include=[np.number])
catalogo_numeric.describe()

,Largo_cm,Ancho_cm,Alto_cm,Volumen_unitario_m3,Peso_unitario_kg
count,900.000000,900.000000,900.000000,900.000000,900.000000
mean,37.969556,24.733111,10.761778,0.018568,2.716397
std,29.248601,17.222106,7.898006,0.028831,3.232846
min,7.600000,4.800000,1.900000,0.000171,0.108000
25%,19.775000,10.100000,5.100000,0.000818,0.453000
50%,26.950000,20.900000,8.100000,0.005290,1.180500
75%,43.225000,33.825000,14.700000,0.022076,3.753250
max,125.900000,72.700000,42.000000,0.121356,13.677000

In [7]:
catalogo_object = df_catalogo.select_dtypes(include=[object])
display(catalogo_object.describe())
print(catalogo_object["Descripción SKU"].unique())
print(catalogo_object["Tipo_embalaje"].unique())

              SKU    Descripción SKU Tipo_embalaje
count         900                900           900
unique        900                 36             3
top     SKU-00001  Alicate universal   Caja propia
freq            1                 41           541

['Martillo carpintero' 'Escalera aluminio 4 peldaños' 'Cinta aisladora'
 'Silicona cartucho' 'Lámpara mesa' 'Monitor 24 pulgadas'
 'Caja herramientas plástica' 'Manguera jardín 20m' 'Router WiFi'
 'Taladro eléctrico' 'Reloj pared' 'Florero cerámica'
 'Teclado inalámbrico' 'Amoladora angular' 'Llave ajustable 8 pulgadas'
 'Rodillo pintura' 'Tarugos nylon bolsa 50u' 'Sierra circular'
 'Cuadro decorativo 60x40' 'Espejo pared 80x60' 'Parlante Bluetooth'
 'Cámara seguridad' 'Cable eléctrico 10m' 'Clavos caja 1kg' 'Mouse óptico'
 'Smartphone caja' 'Alicate universal' 'Notebook 15 pulgadas'
 'Tornillos caja 100u' 'Estantería modular' 'Broca acero 10mm'
 'Tablet 10 pulgadas' 'Interruptor eléctrico' 'Pintura látex 4L'
 'Smart TV 43 pulgadas' 'Pintura látex 1L']
['A granel' 'Embalaje personalizado' 'Caja propia']